### ISSUE TITLE
When will support for ROS2 Humble be added?

### ISSUE THREAD

**Issue by zz0320** [MechMindRobotics/mecheye_ros2_interface#12]
I tried to use Ubuntu 22.04 and ROS2 Humble for the driver, but I encountered a ‘ros2run aborted’ error when running start.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by shuaidang** [comment]
Hello, 
currently, MechEye API supports ROS2 Galactic version, but it does not yet support ROS2 Humble.
![image](https://github.com/MechMindRobotics/mecheye_ros2_interface/assets/109052398/e96183b9-9739-49f3-906c-5c5c9365df86)
