### ISSUE TITLE
Don't working(in ros2 humble, ubuntu22.04)

### ISSUE THREAD

**Issue by Rhymakers** [MechMindRobotics/mecheye_ros2_interface#13]
I have successfully finished colcon build and the latest sdk (meceye2.3.3). But when I ask ros2 run, it says I can't find the camera. Is the sdk version a problem? The supported sdk version seems very low, and the download link isn't working. Does it fit the latest sdk, and is there a plan to support the latest ros2 version?

**Comment by shuaidang** [comment]
Hello, you can try using the latest version of MechEye 2.3.4, which was uploaded recently, and the accompanying ROS routine.

**Comment by Rhymakers** [comment]
Thank you for your response!!
